# Azure Pipelines CI build configuration
# Documentation at https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - 'master'
  tags:
    include:
    - '*'
pr:
  branches:
    include:
    - '*'

jobs:
- job: "Toolchains_RV32IMC"
  displayName: "GCC and Clang/LLVM toolchains targeting RV32IMC (Ibex)"
  pool:
    vmImage: "ubuntu-16.04"
  timeoutInMinutes: 360
  steps:
  - template: "_build-deps.yml"

  - bash: |
      ./build-gcc-with-args.sh \
        "lowrisc-toolchain-gcc-rv32imc" \
        "riscv32-unknown-elf" \
        "/tools/riscv" \
        "-march=rv32imc" "-mabi=ilp32" "-mcmodel=medany"
    displayName: 'Build GCC toolchain'
    env:
      ARTIFACT_STAGING_DIR: $(Build.ArtifactStagingDirectory)

  - bash: |
      ./build-clang-with-args.sh \
        "lowrisc-toolchain-rv32imc" \
        "riscv32-unknown-elf" \
        "/tools/riscv" \
        "-march=rv32imc" "-mabi=ilp32" "-mcmodel=medany"
    displayName: "Build Clang toolchain"
    env:
      ARTIFACT_STAGING_DIR: $(Build.ArtifactStagingDirectory)

  - template: "_upload-artifacts.yml"
    parameters:
      azure_name: rv32imc-toolchains

- job: "GCC_Multilib_Baremetal"
  displayName: "RV64 GCC (Multilib Baremetal)"
  condition: false
  pool:
    vmImage: "ubuntu-16.04"
  timeoutInMinutes: 360
  steps:
  - template: "_build-deps.yml"

  - bash: |
      ./build-gcc-with-args.sh \
        "lowrisc-toolchain-gcc-multilib-baremetal" \
        "riscv64-unknown-elf" \
        "/opt/riscv-baremetal-toolchain"
    displayName: 'Build GCC toolchain'
    env:
      ARTIFACT_STAGING_DIR: $(Build.ArtifactStagingDirectory)

  - bash: |
      ./build-clang-with-args.sh \
        "lowrisc-toolchain-gcc-multilib-baremetal" \
        "riscv64-unknown-elf" \
        "/opt/riscv-baremetal-toolchain"
    displayName: "Build Clang toolchain"
    env:
      ARTIFACT_STAGING_DIR: $(Build.ArtifactStagingDirectory)

  - template: "_upload-artifacts.yml"
    parameters:
      azure_name: gcc-multilib-baremetal

- job: "GCC_Multilib_Linux"
  displayName: "RV64 GCC (Multilib Linux)"
  condition: false
  pool:
    vmImage: "ubuntu-16.04"
  timeoutInMinutes: 360
  steps:
  - template: "_build-deps.yml"

  - bash: |
      ./build-gcc-with-args.sh \
        "lowrisc-toolchain-gcc-multilib-linux" \
        "riscv64-unknown-linux-gnu" \
        "/opt/riscv-linux-toolchain"
    displayName: 'Build GCC toolchain'
    env:
      ARTIFACT_STAGING_DIR: $(Build.ArtifactStagingDirectory)

  - bash: |
      ./build-clang-with-args.sh \
        "lowrisc-toolchain-gcc-multilib-linux" \
        "riscv64-unknown-linux-gnu" \
        "/opt/riscv-linux-toolchain"
    displayName: "Build Clang toolchain"
    env:
      ARTIFACT_STAGING_DIR: $(Build.ArtifactStagingDirectory)

  - template: "_upload-artifacts.yml"
    parameters:
      azure_name: gcc-multilib-linux
